### ISSUE TITLE
Send file to oblivion 

### ISSUE THREAD

**Issue by dmxgit** [zoff99/ToxAndroidRefImpl#100]
Send file: cannot find the file sent. 
Send photo: picture can be viewed in TRIfA but the file cannot be found on the phone. 

#### Your system information:
TRIfA Version: 1.0.19

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: 8.1.0

Device: Samsung J7 phone

#### Please describe your issue in as much detail as possible:
See above

#### Steps for reproducing this issue:
Send a file, search for the file

#### Screenshots (if possible):
Maybe later...

**Comment by Chiitoo** [comment]
One needs to first save the file in TRIfA, which can be done by tapping and holding for a while on the 'avatar' that sent the file (and selecting the export option), on the chat message view.

See also: https://github.com/zoff99/ToxAndroidRefImpl/issues/23
