### ISSUE TITLE
feature request: "text groupchat"

### ISSUE THREAD

**Issue by readyblue** [zoff99/ToxAndroidRefImpl#102]
Please add text group chat option.

Thanks

**Comment by zoff99** [comment]
group chat is (mostly) supported.

**Comment by tmakarios** [comment]
How do we access this feature?  I'm using TRIfA 1.0.27 from F-Droid, and I can't find any way of starting a group chat.  Even if I use another client on another machine to invite my TRIfA identity to an existing group chat, TRIfA appears to silently ignore the invitation.

**Comment by zoff99** [comment]
@tmakarios was the other client qTox? that is a qTox bug, because qTox only ever creates audio groups and never text groups.
you are welcome to code the missing functionality into TRIfA.

**Comment by je-vv** [comment]
Is there a way to work around the groups issue, of not attending invitations to join groups from qtox?  Right now (trifa v. 1.0.27 from f-droid), doesn't support creating groups, and of course then, adding friends to groups.  qtox v. 0.2.10 creates groups, and can invite friends to those groups, and it allows text chatting on the group, so not sure why the comment about not text groups on qtox...  When inviting trifa friends on qtox to a group, simply nothing happens.

If there's no work around the issue, and further development is required (although there might not be enough man power for it)  can this at least remain open?  so at least people can easily understand this is a missing feature in such case.
