### ISSUE TITLE
No Notifications after update to Android 9 (Pie)

### ISSUE THREAD

**Issue by physkets** [zoff99/ToxAndroidRefImpl#103]
#### Your system information:
TRIfA Version: 1.0.21

App from: F-Droid

Android OS Version: 9.0 (Pie) - LineageOS 16.0

Device: (Xiaomi) Mi A1 - (tissot)

#### Please describe your issue in as much detail as possible:
When I was on LineageOS 15.1 (Android 8.1), it worked fine, in that receiving messages would give a notification in the pull-down menu, as well as a 'dot' on the TRIfA icon. But now after the upgrade to 16.0, it no longer does. I have checked the android Notification settings for the app, and they are all turned on. There is also no ringing when a file receive prompt appears.

#### Steps for reproducing this issue:
Receive message or file.

**Comment by vsatmydynipnet** [comment]
+1 same config:

LineageOS 16.0 (Android 9 Pie) no notifications. On my 14.1 tablet all works fine.

Device Samsung A5 2017 (A520F)

**Comment by SergeyDjam** [comment]
Me too Asus Zenfone Max Pro M1 (AOSP 8.1), ASUS Zenfone ZC451CG and ASUS ZenFone A400CG

**Comment by zoff99** [comment]
can you code the fix and make a PR ?

**Comment by vsatmydynipnet** [comment]
sorry, me is not a developer, i came over TRIfA while looking for an P2P encrypted messenger. Tests are fine as long as not on LOS16.0 /Android 9. But without notifications on these ones, its unusable, which is very sad. There is no similiar messenger and Antox was stopped. So no Tox on Android 9.

**Comment by EuphoricCatface** [comment]
No notifications on Pixel 2, Android Pie as well.
App from Google Playstore (app page says version 1.0.21, updated on 2018-11-24)

**Comment by zoff99** [comment]
closed with 1.0.22
