### ISSUE TITLE
stock avatar icon appeared in chat

### ISSUE THREAD

**Issue by madezent** [zoff99/ToxAndroidRefImpl#104]
I was using TRIfA from F-Droid and suddenly some person appeared in a private chat with one of my contacts, see the attached screenshot. Neither of us has any idea who that guy with the sunglasses is. Is there any explanation how that could have happened?

![Screenshot_20190427-143210](https://user-images.githubusercontent.com/11933893/56856676-bae6ac80-695f-11e9-8aca-13290f100e0c.png)

**Comment by zoff99** [comment]
@christianweinz it's the old default avatar image
https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/android-refimpl-app/app/src/main/res/drawable/user_pacific.png
it's most likely a UI bug. did your friend stop the filetransfer?
do you have access to the adb logs?

**Comment by zoff99** [comment]
there is a 2nd one aswell
https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/android-refimpl-app/app/src/main/res/drawable/user_pratikshya.png

**Comment by madezent** [comment]
Sadly the phone was wiped after that incident in a moment of scare of being hacked, so I cannot provide logs. I'd suggest to remove these pictures and replace them by something the average user will immediately recognize as a placeholder.

**Comment by zoff99** [comment]
can you make a PR ?
