### ISSUE TITLE
crash because jni-c-toxcore.so  not match!

### ISSUE THREAD

**Issue by simonwu-os** [zoff99/ToxAndroidRefImpl#105]
#### Your system information:
TRIfA Version:
latest. build from source
App from Google-Play / F-Droid / other:
other
Android OS Version:
9.0
Device:
Pixel
#### Please describe your issue in as much detail as possible:
in MainActivity.java.
there is a native function:
public static native long tox_conference_get_chatlist_size();
but there is no match function in jni-c-toxcore.so, then crashed.

ps:  circle.yaml is not circel 2.0. then automatically compile jni-c-toxcore.so is failed.
#### Screenshots (if possible):
attach screenshots here

**Comment by simonwu-os** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for long com.zoffcc.applications.trifa.MainActivity.tox_conference_get_chatlist_size() (tried Java_com_zoffcc_applications_trifa_MainActivity_tox_1conference_1get_1chatlist_1size and Java_com_zoffcc_applications_trifa_MainActivity_tox_1conference_1get_1chatlist_1size__)

**Comment by zoff99** [comment]
@simonwu-os did you compile the release version (tag) ?

**Comment by zoff99** [comment]
should work now.
for the future always checkout the latest release tag of the source
