### ISSUE TITLE
[BUG] Application crashes when I click the Login/Logout button.

### ISSUE THREAD

**Issue by eraydurmus** [zoff99/ToxAndroidRefImpl#106]
Hi there @zoff99,

#### My system information:
TRIfA Version: 1.0.23 (latest)

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: 9.0

Device: Xiaomi Redmi Note 7

#### Please describe your issue in as much detail as possible:
Application crashes when I click the login/logout button.

#### Steps for reproducing this issue:

1. Open the TRIfa
2. Click on the hamburger menu.
3. Select the Logout/Login button.
4. And you will see the screen freezes and the application stops responding.

#### Screenshots:
![trf](https://user-images.githubusercontent.com/34961616/60968031-bd349200-a324-11e9-9334-d7d8da9158db.gif)
![trifa](https://user-images.githubusercontent.com/34961616/60968045-c45ba000-a324-11e9-8f8a-380d3e734430.jpg)
![trifa2](https://user-images.githubusercontent.com/34961616/60968054-c7ef2700-a324-11e9-85b2-4ab2d4119234.jpg)

**Comment by eraydurmus** [comment]
Are you there @zoff99?

**Comment by zoff99** [comment]
why are you pressing logout right on startup?

**Comment by eraydurmus** [comment]
I was testing the app...

**Comment by Avispa** [comment]
Can confirm that. (See #135 for system info.)

**Comment by ilovelinux** [comment]
> I was testing the app...

Developers hate testers just because they don't use the app properly as you do :laughing: 
Probably it's because you log out before TRiFA logins in
