### ISSUE TITLE
Google Play Store App Outdated

### ISSUE THREAD

**Issue by JeffCarpenter** [zoff99/ToxAndroidRefImpl#108]
#### Your system information:
TRIfA Version: 1.0.21

App from Google-Play / F-Droid / other:
Google Play

#### Please describe your issue in as much detail as possible:
The Play store page reports that the app version is 1.0.21 and was last updated November 24, 2018.

#### Steps for reproducing this issue:
Scroll to the bottom of https://play.google.com/store/apps/details?id=com.zoffcc.applications.trifa

**Comment by zoff99** [comment]
we do no longer publish on the playstore
