### ISSUE TITLE
Work around to adding existing TOX ID ?

### ISSUE THREAD

**Issue by 0181505050** [zoff99/ToxAndroidRefImpl#117]
#### Your system information:
TRIfA Version: 1.0.26

App from Google-Play / F-Droid / other: Fdroid

Android OS Version: 6.0.1

Device: Cat S60

#### Please describe your issue in as much detail as possible:
I already have tox installed on my desktop. Was hoping to find a way to transfer that ID to my phone, there must be a workaround or a file we can manually edit perhaps?

#### Steps for reproducing this issue:
your text here

#### Screenshots (if possible):
attach screenshots here

**Comment by roynico** [comment]
Yes, I think this feature is really needed.
