### ISSUE TITLE
Error:No dependency for integrity assertion

### ISSUE THREAD

**Issue by epwolf** [zoff99/ToxAndroidRefImpl#119]
#### Your system information:
TRIfA Version:1.0.27

App from Google-Play / F-Droid / other:

Android OS Version:

Device:

When I am importing build.gradle, it says:
Gradle 'android-refimpl-app' project refresh failed
Error:No dependency for integrity assertion 'android.arch.core:common:1.1.0:common-1.1.0.jar:d34824b794bc92ff8f647a9bb13a7c73de920de5b47075b5d2c4f0770e9b8bfd'

Android Studio : V2.3.3 
JDK: 1.8.0_131
Gradle: 4.10.2
SDK Platforms: Android API 29
SDK Platform Tools: 29.0.5
SDK Tools: 26.1.1

**Comment by zoff99** [comment]
@epwolf screenshot?
