### ISSUE TITLE
Can not find downloads

### ISSUE THREAD

**Issue by daveblip** [zoff99/ToxAndroidRefImpl#120]
Hello
i just started using trifa. It works fine to chat and download pix but when I download movies I can not find them anywhere.  I also can't find a way to change my downloadfolder.

Itried several filemanagers to find my movies but none can fin d any movie that trifa said I downloaded.

Thanks
David

#### Your system information:
TRIfA Version:

App from Google-Play / F-Droid / other:

Android OS Version:

Device:

#### Please describe your issue in as much detail as possible:
your text here

#### Steps for reproducing this issue:
your text here

#### Screenshots (if possible):
attach screenshots here

**Comment by zoff99** [comment]
everything is stored in encrypted storage. you need to export it (unencrypted) to use it.
in the message view long press avatar and select export.
