### ISSUE TITLE
How to create tox groups?

### ISSUE THREAD

**Issue by je-vv** [zoff99/ToxAndroidRefImpl#121]
#### Your system information:
TRIfA Version:  1.0.27
App from Google-Play / F-Droid / other:  F-Droid
Android OS Version:  9 (LineageOS for MicroG 16.0 from 2020-01-17)
Device:  Xiaomi Redmi 4X (Santoni)

Trifa seems not to pay attention to invitations to tox groups created by qtox.  According to [qtox-comment](https://github.com/qTox/qTox/issues/5960#issuecomment-576053303), it's due to qtox creating type 2 tox groups, whereas Trifa and other clients only supporting type 1.

The suggestion provided was to create the group on Trifa, and then invite qtox friends from Trifa to its created type 1 group, since qtox can join those type 1 groups any ways.

Issue is I can't find a way to creat a tox group from Trifa.

Any help is welcome.

**Comment by zoff99** [comment]
qTox has more contributors, it would make sense they fix their bug.
if you can help code it for TRIfA you are welcome.
otherwise closing this.
