### ISSUE TITLE
Not a issue, but a request: Option to autodisable "Battery Savings Mode" when phone charging.

### ISSUE THREAD

**Issue by migulen** [zoff99/ToxAndroidRefImpl#123]
Location for Option: Settings/General (below "Battery Savings Mode")

Option name: "Autodisable BSM when charging".

It could be very useful. It will disable "Battery Savings Mode" when phone is charging and autoenable "Battery Savings Mode", if it was enable before, when running from battery. 

What do you think about it ?

#### Your system information:
TRIfA Version:

App from Google-Play / F-Droid / other:

Android OS Version:

Device:

#### Please describe your issue in as much detail as possible:
your text here

#### Steps for reproducing this issue:
your text here

#### Screenshots (if possible):
attach screenshots here

**Comment by migulen** [comment]
**@zoff99 I have a working code for this functionality.** I'm going to test it for a week, and if it works correctly I post here... or if I learn how to make a correct branch in github I'll post it there.

**For now I will continue doing Spanish translation.** After that i'll take a look to tox file export/import, but i'm not sure when i can make some functional.

By the way, I've seen that now when you reinstall TRifA over TRifA your old profile isn't lost, is it ?

**Comment by zoff99** [comment]
@migulen add me on Tox. do you have a public ToxID ?
