### ISSUE TITLE
Cannot export and import data

### ISSUE THREAD

**Issue by wangnan789** [zoff99/ToxAndroidRefImpl#128]
#### Your system information:
TRIfA Version:1.0.28

App from Google-Play / F-Droid / other:circleci.com

Android OS Version:6.0.1

Device:samsung s6

#### Screenshots (if possible):
![Screenshot_20200321-005650](https://user-images.githubusercontent.com/22336739/77187303-379dee80-6b0f-11ea-869f-64ff9cdd8b02.png)
![Screenshot_20200321-005701](https://user-images.githubusercontent.com/22336739/77187340-45537400-6b0f-11ea-944d-965e5279a2b4.png)

https://ftp.bmp.ovh/imgs/2020/03/1f54f5f4274a8996.png
https://ftp.bmp.ovh/imgs/2020/03/ac65cb9b799c4848.png

**Comment by wangnan789** [comment]
/data/data/com.zoffcc.applications.trifa/files/savedata.tox
If your phone has root permissions, you can import or export this file anywhere

**Comment by therealmaxmoon** [comment]
This doesn't work. If I export a file, the app crashes and if I put another copy of a tox backup into `/data/data/com.zoffcc.applications.trifa/files/` as `savedata.tox`, the import doesn't do anything.

TRIfa version 1.0.45 (from F-Droid)
