### ISSUE TITLE
Bundled iOS (Apple) emoji artwork is proprietary and probably a legal trouble

### ISSUE THREAD

**Issue by grizzlyuser** [zoff99/ToxAndroidRefImpl#139]
#### Your system information:
TRIfA Version: 1.0.32

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: Doesn't matter

Device: Doesn't matter

#### Please describe your issue in as much detail as possible:
As can be seen from https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/android-refimpl-app/app/build.gradle#L233 , iOS emoji are included in TRIfA. AFAIK, these are proprietary, please see https://github.com/vanniktech/Emoji/issues/433 for details

#### Steps for reproducing this issue:
1. Open TRIfA.
2. Start a chat with any user.
3. Tap emoji icon near the text entry box.
4. Tap any emoji.
5. Send a message.

Expected results:
Emoji that are displayed on steps 3, 4, 5 are only freely licensed (libre) artwork. For example, https://github.com/googlefonts/noto-emoji or any other with similar licensing.

Actual results:
iOS (Apple) proprietary artwork is displayed.

![Screenshot_20200429-104232_TRIfA](https://user-images.githubusercontent.com/45486304/80572895-b720b680-8a07-11ea-8963-24df2eec189a.png)

**Comment by ghost** [comment]
Twemoji by Twitter is released under BY-CA 4.0 (graphics) and MIT (code):
https://twemoji.twitter.com/
https://github.com/twitter/twemoji
preview: https://emojipedia.org/twitter/

Riot-web uses them. The only modern and modern looking emoji I could find with the most options (MIT/BY-CA 4.0). (Interested in alernatives, if anyone knows some.)

**Comment by Nokia808** [comment]
This is really great issue that break the nature of Tox client & making it unsafe ! I think now TRIFA go in same path of Tok-Android !

It is the time to shift from TRIFA to other client, probably aTox ......

**Comment by therealmaxmoon** [comment]
@Nokia808 How does it break the nature of TOX and how does it make it unsafe?

aTox doesn't support audio or video telephony. There are not many open source TOX clients for Android, to be specific... it's 2.

**Comment by Nokia808** [comment]
@therealmaxmoon 
How you know what the CLOUSED source elements containing ??
I removed TRIFA from my device.
Moreover, TRIFA very frequently crash on my Android ! It only work for 1st time that I launch it, then persistently crash till I re-install it again !
Very annoying issue: TRIFA never restore backup of Tox ID created on other devices ! I need to import my already created Tox ID on my qTox but I can not at all !
Developer of TRIFA do not listen to users & their complains, just ignore them or look their issues !
From my side, this is the last replay from me on this repository & I will never open or read or install any thing from it. 

At least aTox developer hear to us & discuss us & he is on the road to add audio/video calls .....
