### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by jbrepogmailcom** [zoff99/ToxAndroidRefImpl#140]
Hello. I understand that any Android keyboard passes keystrokes to the operating system over some API, where it is then picked up by target application over another API. Does that mean that on level of OS any software keyboard can be eavesdropped? Thank you for comment. Jan

**Comment by KOLANICH** [comment]
Surely it does. So can be any hardware keyboard. The OS is explicitly trusted and can do lot of things. If you are making own devices based on own chips produced on own factories by very trusted staff, then you can make a user-controlled TEE though.

**Comment by dpriskorn** [comment]
If you are worried about that I suggest you install Lineage. Its much better than stock Android when it comes to privacy IMO.
