### ISSUE TITLE
Decentralysed push notifications service

### ISSUE THREAD

**Issue by KOLANICH** [zoff99/ToxAndroidRefImpl#149]
**Is your feature request related to a problem? Please describe.**
Apps have to use centralised services to deliver push notifications. Centralised push notifications services have freedom issues. Parties having apps using them depend on the services.

**Describe the solution you'd like**
The idea was to replace centralysed push notifications services with decentralysed Tox-based ones - apps register with the provider implemented within TRIFA and get Tox addresses, then these Tox addresses can be used by other apps on other devices (including servers) to send them push notifications.

**Your system information:**
 - TRIfA Version: Any
 - App from Google-Play / F-Droid / other: Any
 - Android OS Version: Any with push notifications middleware
 - Device: Any with push notifications middleware

**Describe alternatives you've considered**
Haven't.

**Additional context**
I remember I have left an issue about this in Antox repo (probably a one by Mark Winter, which 
has issues disabled currently) , but the authors have said it is out of scope. Is it out of scope for you too?

**Comment by TillOk** [comment]
This issue does not follow the standards and should be closed
