### ISSUE TITLE
photo data leak

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#153]
being in a chat with a contact and hitting the icon for sending a file and selecting a photo from the saved camera photos results in a black and white preview image for the receiver before he accepts the transfer. The problem is that that preview image was not of the image being sent but of a DIFFERENT photo taken just BEFORE the photo being sent.
And yes, I know that I did not accidentally send the wrong photo, because after accepting the transfer, the correct photo was transmitted and not the one of the b/w preview

**Comment by zoff99** [comment]
all issues not using the proper template will be closed
