### ISSUE TITLE
sending files other thatn photos does not work.

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#154]
I can send photos just fine, but if I want to send e.g. a pdf file, nothing happens.
Steps to reproduce: Open trifa, enter a chat with a contact, tap on the file send icon, chose a pdf file.
Result: You're back to the chat. No transfer happening, no error message. 
Expected result: a dialog asking if you really want to send the file and upon clicking 'yes', the file being sent to the contact.

**Comment by zoff99** [comment]
all issues not using the proper template will be closed
