### ISSUE TITLE
selecting more than one photo for transfer does not work

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#155]
I can directly chose one photo to send by tapping on it.
I can also long tap on it and it gets selected. It then says "selected 1". Tapping on another image selects that one and unselects the previous one, text still reading "Selected: 1"
Expected behaviour: After tapping a second (third, ...) image, that is selected IN ADDITION to previously selected ones (i.e. without unselecting previous ones) and text reading "Selected: 2 (3, 4, ...)"

**Comment by zoff99** [comment]
all issues not using the proper template will be closed
