### ISSUE TITLE
please rename "firends" to "contacts"

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#159]
"contacts" is the more adequate word since people can be using Trifa not only with friends but with very heterogenous sets of contacts, such as friends, family, business partners, neighbors, ....

**Comment by zoff99** [comment]
all issues not using the proper template will be closed

**Comment by TillOk** [comment]
This is just silly.
Instead of being grateful for user feedback.
Or are you trying to tell me that you do device-specific wording in Triff?
