### ISSUE TITLE
Missing a QR Code and copy&paste for ID

### ISSUE THREAD

**Issue by vv01f** [zoff99/ToxAndroidRefImpl#16]
I have the option to scan a QR when adding a contact.
But my own ID is just shown in a label that I cannot mark/copy so send it over.

**Comment by zoff99** [comment]
you ToxID can be copied on your profile page.
just select it (by long clicking on the letters).

it's not perfect yet, but it can be selected

**Comment by vv01f** [comment]
Ah, didn't see the other view before. Swiping from left revealed it then.
