### ISSUE TITLE
nospam BUG

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#161]
**Describe the bug**
upon adding a new contact, the nospam changes automatically, thus invalidating the toxid I give out on printed cards.
Expected behaviour: New contacts can be added or Friend requests accepted without a chnge to the nospam value.

**To Reproduce**
1. Go to 'Trifa'
2. Copy your ToxID
3. Click on a TokGroupchat'
4. Give someone your ToxID
5. Ask that someone to add you
6. Wait until you get a "FriendRequest"
7. Accept the "FriendRequest"
8. Check your ToxID
9. Look at the end of the ToxID
10. See that the nospam value has changed

**Expected behavior**
Expected to happen is to see the same ToxId as before.
The nospam value should ONLY change after a change was explicitly authorised by the user because it renders the user's ToxID useless. People want to be able to share their ToxID on their cards or github profiles, websites, …

**Your system information:**
 - TRIfA Version: [1.0.61]
 - App from Google-Play
 - Android OS Version: Android 8
 - Device: Huawei P10

**Add screenshots, if possible**
No

**Additional context**
Tried on a Friday in a leap year.

**Comment by zoff99** [comment]
this is not a bug, it's a feature.
to disable go to the settings.
