### ISSUE TITLE
wrong preview displayed for photo filetransfer

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#162]
**Describe the bug**
being in a chat with a contact and hitting the icon for sending a file and selecting a photo from the saved camera photos results in a black and white preview image for the receiver before he accepts the transfer. The problem is that that preview image was not of the image being sent but of a DIFFERENT photo taken just BEFORE the photo being sent.
And yes, I know that I did not accidentally send the wrong photo, because after accepting the transfer, the correct photo was transmitted and not the one of the b/w preview

**To Reproduce**
1. Take your Android Device on which Trifa is installed
2. Take several easily distinuishable photos with the camera
3. Open TRiffa
4. Go to a chat
5. Tap on the file send symbol
6. Select the place your camera stores the photos
7. Select a photo
8. Remember which photos is selected
9. On the receiving end, see the preview
10. See that it shows a different photo in black and white.

**Expected behavior**
The photo you sent should be in the preview and not a different photo

**Your system information:**
 - TRIfA Version: [1.0.61]
 - App from Google-Play
 - Android OS Version: Android 8
 - Device: Huawei P10

**Add screenshots, if possible**
No

**Additional context**
Tried on a Friday in a leap year.

**Comment by GrayHatter** [comment]
@zoff99 FYI this is a pretty critical security bug, not just privacy leak

**Comment by zoff99** [comment]
i can't reproduce that. can you attach the adb logs?
do you have a custom ROM installed? any Xposed modules or such?

**Comment by zoff99** [comment]
@TillOk what client is used as the receiver?

**Comment by zoff99** [comment]
still cant reproduce this, and no other person has confirmed the issue to me.
without more details its hard to check what your issue was.

**Comment by GrayHatter** [comment]
@zoff99 probably safe to close this now as can't reproduce, and hope if it is a real bug someone else can provide enough info to find/fix it.

**Comment by zoff99** [comment]
I think I may have found the underlying issue. the good news is that it's sort of a UI bug with Glide and RecyclerView.
It's hard to debug since it occurs only in very few edge cases.

I still could not see how a photo would be suddenly showing up in black and white, when it's normally in color
