### ISSUE TITLE
sending files other than photos does not work

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#163]
**Describe the bug**
I can send photos just fine, but if I want to send e.g. a pdf file, nothing happens.
Steps to reproduce: Open trifa, enter a chat with a contact, tap on the file send icon, chose a pdf file.
Result: You're back to the chat. No transfer happening, no error message.
Expected result: a dialog asking if you really want to send the file and upon clicking 'yes', the file being sent to the contact.

**To Reproduce**
1. Take your Android device on which Triff is installed
2. Unlock the screen
3. Open Trifa
4. Go to a chat with an online contact
5. Tap on the file send symbol
6. Select a non-photo file, e.g. a pdf.
7. You're back to the chat and nothing has happened

**Expected behavior**
A clear and concise description of what you expected to happen:
Clearly, I expect the file to be sent.

**Your system information:**
 - TRIfA Version: [1.0.61]
 - App from Google-Play
 - Android OS Version: Android 8
 - Device: Huawei P10

**Add screenshots, if possible**
No

**Additional context**
Tried on a Friday in a leap year.

**Comment by zoff99** [comment]
can not reproduce this.

**Comment by zoff99** [comment]
this should be fixed with the latest release.
some people have reported that their default android included file manager would not show all filetypes to select.
this was fixed by installing a different file explorer.
but that seems to have been an edge case.
