### ISSUE TITLE
BUG: sharing via Android sharing does not work

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#164]
**Describe the bug**
if I am in my gallery and select "share" and then "TRIfA" , it opens trifa with a blank screen with only the text "Share Content …", nothing else happens or is doable except leaving.
expected behaviour: trifa asks with which contact you want to share the given content, and then sends it to that contact.

**To Reproduce**
1. Take your Android phone on which Triffa is installed
2. Unlock the screen
3. Find your gallery
4. Open your gallery
5. Choose a photo
6. open that photo
7. tap on "share" icon
8. select "open with Trifa"
9. See the error: a whiite screen with text "Share Content …"

**Expected behavior**
Clearly, I expected to be asked by Trifa with which contact I want to share the photo, and that after I select one, that contact will receive the photo.

**Your system information:**
 - TRIfA Version: [1.0.61]
 - App from Google-Play
 - Android OS Version: Android 8
 - Device: Huawei P10

**Add screenshots, if possible**
No

**Additional context**
Tried on a Friday in a leap year.

**Comment by zoff99** [comment]
this should be fixed with the latest release
