### ISSUE TITLE
BUG: selecting more than one photo for transfer does not work

### ISSUE THREAD

**Issue by TillOk** [zoff99/ToxAndroidRefImpl#166]
**Describe the bug**
You cannot select more than one photo for sending.
I can directly chose one photo to send by tapping on it.
I can also long tap on it and it gets selected. It then says "selected 1". Tapping on another image selects that one and unselects the previous one, text still reading "Selected: 1"
Expected behaviour: After tapping a second (third, ...) image, that is selected IN ADDITION to previously selected ones (i.e. without unselecting previous ones) and text reading "Selected: 2 (3, 4, ...)"

**To Reproduce**
1. get an Android phone
2. install Trifa on it
3. Take several photos
4. Open Trifa
5. Install Trifa on another device
6. Add the other device as a contact on the first device
7. open Trifa on both devices
8. Wait until they see each other as online
9. On device #1, open a chat with device #2 
10. On device #1, tap on the file send icon
11. navigate to your photos
12. long tap on one of the photos
13. now tap on another photo
14. you see that now the first photo is not selected and only the second photo you tapped on is selected

**Expected behavior**
Clearly, I want both photos to be selected and then sent

**Your system information:**
 - TRIfA Version: [1.0.61]
 - App from Google-Play
 - Android OS Version: Android 8
 - Device: Huawei P10

**Add screenshots, if possible**
No

**Additional context**
Tried on a Friday in a leap year.

**Comment by zoff99** [comment]
this should be solved now with the latest release
