### ISSUE TITLE
TRIfA stays offline after interruption of connection

### ISSUE THREAD

**Issue by toxtox** [zoff99/ToxAndroidRefImpl#17]
I guess this is a well known issue and the reason for the _"Logout/Login"_-button.
The automatic refresh/relogin should be easy to fix for you because I remember that you have fixed it for Antox some time ago ;-)  (https://github.com/Antox/Antox/pull/292)

**Comment by SergeyDjam** [comment]
Yes, I have the same problem. But it only exists if the 3G channel is used.

**Comment by toxtox** [comment]
@SergeyDjam  I guess you will have the same problem with wireless LAN and "normal" LAN, too. The chance that TRifA goes online again after an interruption of connection depends on the duration of the interruption. (This was the case with older Antox versions [see Antox-link above and the results table in this issue])

**Comment by zoff99** [comment]
fixed in 1.0.9
0670c73d67311afbe99cc15fead24f3e1c9fcaaa

**Comment by toxtox** [comment]
@zoff99 Thanks for working on this bug. But unfortunately I cannot confirm that is fixed completely in 1.0.9 yet.
Before TRIfA 1.0.8 never reconnected automatically after interruption of connection. I had to always press the "_Logout/Login_"-button for reconnection. 
Now TRIfA 1.0.9 reconnects sometimes. But the main **problem** is that the **contacts stay often "offline"** even when the contacts (in my case a qTox contact-profile) are online.

# Test 1:
- delay to detect interruption: Antox 26s; TRIfA 71s
interruption duration 135s
- delay to reconnect: Antox 40s; TRIfA 57s
- delay to receive text message from qTox (message was send when Antox and TRIfA were offline): Antox 34s; TRIfA 57s

# Test 2:
- delay to detect interruption: Antox 32s; TRIfA 75s (But TRIfA-status changed after 21s from "_TCP_" to "_UDP_" before it changes to "_offline_" this is strange)
interruption duration 600s
- delay to reconnect: Antox 40s; TRIfA 60s
- delay to receive text message from qTox (message was send when Antox and TRIfA were offline): Antox **FAILED**; TRIfA **FAILED** (no message after 360s, clients say "online" but contacts stay "offline" )

=> Conlusion: The reconnection behavior seems to be still unreliable (Antox and TRIfA). Maybe interruption duration has an influence on successful reconnection.

(MOKEE  6.01 on XT894, qTox nightly 4.Dec.2016)

**Comment by toxtox** [comment]
@zoff99 

# Test 3:
The same test as above but with latest **µTox** (0.16.1 alpha binary for Linux, TCP) instead of old **qTox** as client for sending messages to Antox and TRIfA when these two Android-Clients are offline. Antox and TRIfA were restarted just before the test run to avoid any "aging"-effects.

- delay to detect interruption ("OFFLINE"-status): Antox 23s; TRIfA 73s (But TRIfA-status changed after 14s from "TCP" to "UDP" before it changes to "offline" this is strange)

interruption duration 600s

- delay to reconnect: Antox 25s; TRIfA 12s
- delay to receive text message from µTox (message was send when Antox and TRIfA were offline): Antox 35s; TRIfA 85s

# Test 4:       ( Test 4 = Test 3 repeated for a second time)
- delay to detect interruption ("OFFLINE"-status): Antox 27s; TRIfA 74s (But TRIfA-status changed after 6s from "TCP" to "UDP" before it changes to "offline" this is strange)

interruption duration 600s

- delay to reconnect: Antox 36s; TRIfA 16s
- delay to receive text message from qTox (message was send when Antox and TRIfA were offline): Antox **FAILED**; TRIfA **FAILED** (no message after 600s, clients say "online" but contacts stay "offline" )

- pressing manually the "_Logout/Login_"-button: all contacts in TRIfA are online again and TRIfA gets the message from µTox-friend-contact.

=> Conclusion: Same result as before with the old µTox-version. Obviously the risk that the test fails seems to be higher on the second test without any Logout/Login-events in between these two tests. This behavior looks like an **_"aging"-effect_** of Antox and TRIfA ;-)

@SergeyDjam : Can you confirm/reproduce these test results?

**Comment by toxtox** [comment]
@zoff99 

# Test 5: (same test as Test 3 but with UDP in Antox TRIfA, and µTox instead of TCP)
- delay to detect interruption ("OFFLINE"-status): Antox 20s; TRIfA 74s

interruption duration 600s

- delay to reconnect: Antox 1s; TRIfA 16s
- delay to receive text message from µTox (message was send when Antox and TRIfA were offline): Antox 42s; TRIfA 76s

# Test 6:  (Test 6 = Test 5 repeated for a second time)
-delay to detect interruption ("OFFLINE"-status): Antox 35s; TRIfA 75s 

interruption duration 600s

- delay to reconnect: Antox 1s; TRIfA 2s
- delay to receive text message from qTox (message was send when Antox and TRIfA were offline): Antox **FAILED**; TRIfA **FAILED** (no message after 600s, clients say "online" but contacts stay "offline" )

- pressing two-times manually the "Logout/Login"-button: all contacts in TRIfA are online again and TRIfA gets the offline message from µTox-friend-contact.

**=> Conclusion:** Same result and **"_aging"-effect_** at second 600seconds-interruption with TCP and UDP.

**Comment by toxtox** [comment]
@zoff99 
Thanks for fixing this issue. Now in 1.0.14 it is really reliable!
