### ISSUE TITLE
Specify bootstrap node

### ISSUE THREAD

**Issue by linsui** [zoff99/ToxAndroidRefImpl#170]
**Is your feature request related to a problem? Please describe.**
The default bootstrap nodes may be not accessible, I hope that I can use my friends' nodes as bootstrap nodes.

**Describe the solution you'd like**
A field to specify boootstrap nodes.

**Your system information:**
 - TRIfA Version: [1.0.62]
 - App from Google-Play / F-Droid / other: [F-Droid]
 - Android OS Version: [e.g. Android 9]
 - Device:

**Comment by ghost** [comment]
~is it still relevant?~

the option is available thru settings
