### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [zoff99/ToxAndroidRefImpl#173]
Ref: https://f-droid.org/wiki/index.php?title=com.zoffcc.applications.trifa/lastbuild_10068&oldid=274653

**Comment by zoff99** [comment]
@licaon-kter any idea how to fix it. all CI builds of trifa run into this, but my local Android Studio builds it just fine

**Comment by licaon-kter** [comment]
Can you build from command line outside AS?

**Comment by zoff99** [comment]
locally yes. also a friend on a different computer can build it with AS.
only CIs get this error.
no idea what to do here.

**Comment by zoff99** [comment]
using a workaround now. so this is no longer valid.
