### ISSUE TITLE
TRIfA not compatible with replicant

### ISSUE THREAD

**Issue by ghost** [zoff99/ToxAndroidRefImpl#177]
**Describe the bug**
I'm using replicant-6.0, 3.0.101-replicant kernel. They are working on replicant 9, thus I'll wait this version to upgrade.

The TRIfA working version is 1.0.49
After this version, the program crashes when trying to add a new contact, using the toxID.

After that, it crashes all the time, and can't start again.

**To Reproduce**

Add contact by clicking on the "+", then entering the toxID.

App from f-droid

My phone is Samsung Galaxy S3 i9300

Sorry, I can't make screenshots for now.

**Comment by ghost** [comment]
Hello,

There is the output of adb logcat:

https://copycat.drycat.fr/?2c17a66887252120#BibHRp4mDSB8Uj81GBnraXmGRMmDFLtmpiaZ5VRMV4Ue

**Comment by DaKnig** [comment]
@millerebonds the link is dead. please upload to some place that would not expire.

**Comment by zoff99** [comment]
@millerebonds does this work now with the lastest version 1.0.91 ?

**Comment by ghost** [comment]
Yes, it works

**Comment by zoff99** [comment]
@millerebonds so i am closing this issue if it works now
