### ISSUE TITLE
Latest grapheneos build cant send images

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [zoff99/ToxAndroidRefImpl#181]
Anyone else experiencing this?

**Comment by hp8wvvvgnj6asjm7** [comment]
![IMG-20200920-WA0001](https://user-images.githubusercontent.com/45887282/93713329-51220080-fb5b-11ea-9243-abe548150e94.jpg)

**Comment by zoff99** [comment]
@hp8wvvvgnj6asjm7 if you press the green arrow, does the file send or not? or is just the preview broken?

**Comment by hp8wvvvgnj6asjm7** [comment]
@zoff99 it attempts to load the image, the recipient receives the image loading request, but then he gets the loading sign which disappears. The problem is on the senders side, we tried sending to multiple devices running tox clients.
The image above is as seen from the sender's side on grapheneOs. After pressing the green button, the image attempts to send but then cancels.

Receiving images works.

**Comment by hp8wvvvgnj6asjm7** [comment]
If I try to send, it goes up to 94% and then cancels.

**Comment by firen777** [comment]
> @zoff99 it attempts to load the image, the recipient receives the image loading request, but then he gets the loading sign which disappears. The problem is on the senders side, we tried sending to multiple devices running tox clients.
> The image above is as seen from the sender's side on grapheneOs. After pressing the green button, the image attempts to send but then cancels.
> 
> Receiving images works.

Not a GrapheneOS user, but I had a similar issue where the image failed to render on the sender side. And I can receive image without problem. I did, however, manage to send the image to my other qTox client.

That "image" qTox received, however, is just a file filled with "0x00" byte with the same size as the original file. I'm wonder if this is the problem with the Android 10 file picker as I have no such problem with my other Android 9 phone.

**Comment by hp8wvvvgnj6asjm7** [comment]
yes it looks similar to my issue i get an empty file.
i think this means that the filestream opens, but doesnt get any data, so what remains is the 0x00.

**Comment by hp8wvvvgnj6asjm7** [comment]
@zoff99 it seems that trifa version 1.0.21 doesn't have this issue.  Is it possible to merge the parts of the code which fix this?
