### ISSUE TITLE
feature request: option to import and export the user profile

### ISSUE THREAD

**Issue by toxtox** [zoff99/ToxAndroidRefImpl#19]
@zoff99 : I guess this feature is already on your TODO-list.
By the way I suppose I will get in trouble when I try to copy my (encrypted?) profile with an unknown password (I have choosen _"skip"_ at first startup at passwort-setting-step) to an other device.
The reason for choosing "_skip_" is that I start TRIfA automatically on Android startup without the need for entering a password.
Maybe it will be possible to export the profile unencrypted?

**Comment by zoff99** [comment]
@toxtox as long as you copy your preferences file and your toxsavefile it will work.
when you press skip the passwort will be cleartext in the preferencesfile of the app.
if you want it to be secure you need to enter a password manually!

**Comment by toxtox** [comment]
Thank you for this information. This could be a workaround for me until the profile import/export function is included.

**Comment by bentolor** [comment]
I would like to share/use my identity in different clients. I used a password on profile creation. Will this work? Where would I find the current profile files?

**Comment by DoctorSubtilis** [comment]
I'd like import my existing profile in Trifa.

**Comment by zoff99** [comment]
@DoctorSubtilis you are welcome to implement this functionality in TRIfA and sumbit a pull request

**Comment by DoctorSubtilis** [comment]
Done (I hope, at least) !
Thank you

**Comment by ToxChat** [comment]
So, will it be such feature in this client? Wery bad for Tox client not to have import/export in GUI.

**Comment by Avispa** [comment]
**zoff99**:
> as long as you copy your preferences file and your toxsavefile it will work.

... and where do we find those files?

**Comment by zoff99** [comment]
fixed in https://github.com/zoff99/ToxAndroidRefImpl/commit/adc66cad2b963dc9e1d91f4f7e8cfebcea84f944
