### ISSUE TITLE
Crash on !callme & !videocallme

### ISSUE THREAD

**Issue by 0xlne** [zoff99/ToxAndroidRefImpl#20]
Working fine except for the crash on initializing audio/video test.
Device: Xiaomi Mi MIX on Android 7.1.2
The same issue is encountered on a Nexus 9 tablet, Android 7.1.2

Issue not present on Samsung Galaxy A5 (2016) on Android 7.0

Log: 
[trifa_crash.txt](https://github.com/zoff99/ToxAndroidRefImpl/files/1277887/trifa_crash.txt)

**Comment by zoff99** [comment]
@0xlne what version of TRIfA did you use?

**Comment by Roman5x3** [comment]
No issues on Nexus 6P running Oreo 8.0.0 and TRIFA 1.0.8

**Comment by SergeyDjam** [comment]
ASUS Zenfone T00I, Android 5.0, TRiFA 1.0.8 crash too

**Comment by zoff99** [comment]
@0xlne i think this is the problem in your trace:
*Camera2-Parameters: set: Requested preview FPS range 15 - 15 is not supported*

**Comment by zoff99** [comment]
try with the latest snapshot:
https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/README.md

and turn "set fps" option "off"

**Comment by zoff99** [comment]
@0xlne is this fixed for you?

**Comment by 0xlne** [comment]
@zoff99 Yes, this is fixed now (at least in the dev003 branch).
My apologies for not responding earlier; I was moving & had issue connecting outside of work ;]
