### ISSUE TITLE
Putting a password ends up locking you out later on

### ISSUE THREAD

**Issue by a4h7** [zoff99/ToxAndroidRefImpl#207]
**Describe the bug**
If you add a password when you first start the app, later on if you exit the app and return it will not accept the password that you initially set. It has also happened to me that I did not even exit the app, just opened it to use it and was greeted with the password enter screen to which I was locked out. 

**To Reproduce**
1. Set password when first starting app
2. Give it some time maybe an hour (edit: tested this a couple of minutes after and it has these ill effects) (I have tested exiting immediately after and the password will work), exit, and then try to get back in, you will be unable to. When you enter correct password you will get a screen that says Migrating database files, DO NOT close this screen

**Expected behavior**
Password should be able to let you login to your account anytime.

**Your system information:**
 - TRIfA Version: [1.0.83]
 - App from F-Droid
 - Android OS Version: 11
 - Device: Pixel 5

**Add screenshots, if possible**

**Additional context**

**Comment by zoff99** [comment]
this should be fixed in the lastest release
