### ISSUE TITLE
ability to save received file(s)

### ISSUE THREAD

**Issue by readyblue** [zoff99/ToxAndroidRefImpl#23]
Hi,

can you please add option to save received file(s)?

Thanks

**Comment by zoff99** [comment]
@readyblue what version are you using?

**Comment by readyblue** [comment]
@zoff99 latest version from F-Droid, running on Android Nougat 7.1

**Comment by readyblue** [comment]
@zoff99 1.0.8 TRIfA

**Comment by zoff99** [comment]
@readyblue select the message by long clicking on the avatar icon, then on the top bar select "save" icon

**Comment by readyblue** [comment]
@zoff99 oh man, Thank You very much, it is working.

**Comment by physkets** [comment]
It is slightly non-intuitive that only a long-press on the avatar-symbol of that message works as a selection. Can it be made to work if the long-press is anywhere on the message?

Also, I can't find where it put the file. It just says "messages exported" when I click on the save icon after long-presssing. It would be nice if it specified the location.

**Comment by SoberDude** [comment]
I'm also having problems finding the files that are saved.

TRIfA 1.0.21
Android 7.0
LG V20

**Comment by SoberDude** [comment]
Just figured it out using Root Browser

Storage->self->primary->Android->data->com.zoffcc.applications.trifa->vfs_export

Then it's arranged by the Tox ID of your conversation. Hard to find, but it's there.

Love TRIfA by the way. Way better than Antox!

**Comment by zoff99** [comment]
hi guys thanks for the nice words.
we would need more devs to help out, then all these nice things could be implemented.
it's people doing this in there spare time.

**Comment by physkets** [comment]
@SoberDude So do I need to have a rooted phone to access the files? Mine is not.

**Comment by linsui** [comment]
@zoff99  It will be more convenient if I can export file to a custom location. :joy:
