### ISSUE TITLE
opening files still broken

### ISSUE THREAD

**Issue by DaKnig** [zoff99/ToxAndroidRefImpl#230]
**Describe the bug**

the recent update is said to have fixed opening files that are not images. pressing a file that's not an image still does not work- it now just presents a different file.

**To Reproduce**
1. Go to 'a chat'
2. Click on 'a non image file you received'
3. See error - notice a different file.

**Expected behavior**

click on a non image file. the file is opened in an app that can support it, like a video/audio file in vlc .

**Your system information:**
 - TRIfA Version: [1.0.91]
 - App from F-Droid
 - Android OS Version: Android 8
 - Device: Galaxy s8

**Add screenshots, if possible**
(imagine some different image in a screenshot)
**Additional context**
(none)

**Comment by zoff99** [comment]
"the recent update is said to have fixed opening files that are not images" --> who said this?
what you describe is not a bug. you must export the file from encrypted storage first by long clicking on it.
