### ISSUE TITLE
Fastlane directory uses invalid names for some locales

### ISSUE THREAD

**Issue by linsui** [zoff99/ToxAndroidRefImpl#253]
**Describe the bug**
[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags, which use a `-` as the separator rather than `_`. There are a number of locales that use the `_` here. Please rename those dirs to use `-`. Thanks!

For reference: F-Droid downstream [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2323).

**Comment by zoff99** [comment]
@linsui translations come from weblate. if there should be an error please report to weblate.

https://hosted.weblate.org/

**Comment by linsui** [comment]
It's already reported. See https://github.com/WeblateOrg/weblate/issues/5522 . But I doute that even it's fixed upstream, will created translation be fixed. So please fix it here and weblate will just sync it. Thanks!

**Comment by zoff99** [comment]
@linsui what translation from TRIfA does it affect? is a translation missing for you?

**Comment by linsui** [comment]
Only pt_BR is affected.

**Comment by zoff99** [comment]
thanks. what code should pt_BR be for google play store?

**Comment by linsui** [comment]
`pt-BR`.

**Comment by zoff99** [comment]
seems to be ok for f-droid listing:
https://f-droid.org/pt_BR/packages/com.zoffcc.applications.trifa/

**Comment by linsui** [comment]
The fdroidserver does not filter the locale code. But the client won't display them.

**Comment by zoff99** [comment]
https://play.google.com/store/apps/details?id=com.zoffcc.applications.trifa&hl=pt&gl=BR

play store seems show it also

**Comment by zoff99** [comment]
so you mean the problem is only in the f-droid client?

**Comment by zoff99** [comment]
can u contact me on tox?

**Comment by linsui** [comment]
The locale tag is invalid for fastlane but I don't know if it works with Google Play. F-Droid client doesn't display them because it's regard as another language different from the device language.

**Comment by linsui** [comment]
Currently I don't use tox because the network connection is unstable for me...

**Comment by linsui** [comment]
In fact device with pt-BR language will see pt metadata as fallback.

**Comment by zoff99** [comment]
ok lets see what happens ...

**Comment by zoff99** [comment]
lets see if weblate will now explode or what not ...

**Comment by zoff99** [comment]
@linsui but the in-app translations for brazil are working , right?

**Comment by linsui** [comment]
Yes, only fastlane is affected. So the only problem is that pt-BR users will see pt metadata.

**Comment by zoff99** [comment]
ok then. i renamed the directory for fastlane.
lets close the issue for now.
if you find a problem again please open a new issue.

thanks for bringing it to my attention.

**Comment by linsui** [comment]
Thanks!
