### ISSUE TITLE
Disable screenshots option

### ISSUE THREAD

**Issue by s99h** [zoff99/ToxAndroidRefImpl#261]
**Is your feature request related to a problem? Please describe.**
This feature request isn't directly connected to a problem. It's just to improve privacy.

**Describe the solution you'd like**
It would be nice to have an option to disable screenshots in the settings menu.

**Your system information:**
 - TRIfA Version: [1.0.95]
 - App from Github
 - Android OS Version: [Android 7.0]
 - Device: Huawei Mate 9
 
Thank you!

**Comment by zoff99** [comment]
fixed in 69218c483db08ea872edf23fae57d74e32ca945d
