### ISSUE TITLE
Consider migrating to libera.chat instead freenode

### ISSUE THREAD

**Issue by samuraikid0** [zoff99/ToxAndroidRefImpl#276]
Freenode now belong to lee, it isn't the open source it was to be so the old staff pee on lee and created libera.chat 

Cheers

**Comment by zoff99** [comment]
@samuraikidXDA already did. can you point me to where there is still a reference to freenode?
trifa itself does not link to an IRC channel

**Comment by zoff99** [comment]
no more response, so I'm closing it.
