### ISSUE TITLE
Calls crash from binary-source TRIfA on Broadcom/OpenMAX-based device; source-built TRIfA works fine

### ISSUE THREAD

**Issue by zer0def** [zoff99/ToxAndroidRefImpl#278]
**Describe the bug**
Any attempt of an AV call (be it video, or audio-only) with TRiFA causes the client to crash after brief start.

**To Reproduce**
Initiating or answering a video or audio call from the Android device or from desktop side leads to the crashing result.

**Your system information:**
 - TRIfA Versions:
   - Github releases, 1.0.106
   - F-Droid 1.0.108
   - F-Droid 1.0.109
 - Android OS Version: [e.g. Android 7.1/LineageOS 14.1]
 - Device: Samsung GT-I9082

**Additional context**
Logcat outputs attached.
[vcall-answer.log](https://github.com/zoff99/ToxAndroidRefImpl/files/6722290/vcall-answer.log)
[vcall-initiate.log](https://github.com/zoff99/ToxAndroidRefImpl/files/6722291/vcall-initiate.log)
[tombstone_00.log](https://github.com/zoff99/ToxAndroidRefImpl/files/6722332/tombstone_00.log)
[tombstone_01.log](https://github.com/zoff99/ToxAndroidRefImpl/files/6722333/tombstone_01.log)

**Comment by zer0def** [comment]
Per instructions agreed upon elsewhere, rebuilding TRiFA with all instances of `NativeAudio.PlayPCM16(NativeAudio.n_cur_buf);` commented out fixes the issue, making video and audio calls working without a hitch.

**Comment by zoff99** [comment]
@zer0def thats partly good news. now just need to find out how to fix the crash.
it could be a bug in lineageos for that device.

let me think of a way to find the exact position where the actual problem is.

**Comment by zoff99** [comment]
@zer0def can you checkout trifa source again (latest from github), i added a few debugging lines.
https://github.com/zoff99/ToxAndroidRefImpl/commit/9c5528c3285c2e746b7d3b92d6323cbc3eb059c3
and leave the ```NativeAudio.PlayPCM16``` calls active.

check if you get ```PlayPCM16:``` log lines in ```adb logcat```
hopefully it will show the problem

**Comment by zer0def** [comment]
[trifa-9c5528c3-logcat.log](https://github.com/zoff99/ToxAndroidRefImpl/files/6735945/trifa-9c5528c3-logcat.log)

**Comment by zoff99** [comment]
the log does not seem to show a crash. is calling working now?

**Comment by zer0def** [comment]
Strangely enough, *yes*, though you can periodically hear a loud crackle.

EDIT: In case it's useful for bisection, the crash still occurs on TRIfA 1.0.109 from F-Droid. Current `dev003` head works fine.

EDIT2: Source builds going as far back as tag 1.0.108 seem to be working fine.

**Comment by zoff99** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9326

newer NDK and cmake seem to fix the issue. let's see if the next official f-droid release will really fix it.

**Comment by zer0def** [comment]
Fixed in 1.0.111 - audio and video calls work correctly without crashing the Android client.
