### ISSUE TITLE
New contact adds automatically without asking to approve

### ISSUE THREAD

**Issue by pizdjuk** [zoff99/ToxAndroidRefImpl#302]
New contact adds automatically without asking to approve

**To Reproduce**
1. Give your ToxID to somebody
2. Somebody need to add you as a friend
3. the contact added automatically without approving

**Expected behavior**
The contact need to be accepted as a friedn

**Your system information:**
 - TRIfA Version: [1.0.119]
 - App F-Droid
 - Android OS Version: MIUI 10.1

**Additional context**

The issue is a severe security issue, since the IP can be leaked to every person knowing a ToxID

**Comment by zoff99** [comment]
the nospam is changed on every new contact, so your ToxID is only working once to add a new friend.
To add the next friend you need to use your new ToxID.

if you change the default setting, a big red warning is displayed.

Also the default for TRIfA is TCP only mode, so your IP address is never known to any added friend.

In general Tox does not have the goal to hide your IP address, see: https://tox.chat/faq.html#tox-leak-ip
```Tox makes no attempt to cloak your IP address when communicating with friends ...```

To hide your IP address with TRIfA use Orbot.

**Comment by pizdjuk** [comment]
As far as I know, the tox-protocol doesnt allow to know the IP-Adress till the person is not added as a friend
