### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by stemy2** [zoff99/ToxAndroidRefImpl#31]
#### Your system information:
TRIfA Version: 1.0.11

App from Google-Play / F-Droid / other: F-droid

Android OS Version: 7.1.2

Device: Samsing Galaxy S7

#### Steps for reproducing this issue: It can happens if you make any of the following actions:
-open the app
-click on «profile»
-select one of your contacts

**Comment by stemy2** [comment]
Reinstalled the app, solved the problem.

**Comment by zoff99** [comment]
this can happen in rare cases. it is enough if you go to your android system settings and force-stop TRIfA. and then start it again

**Comment by stemy2** [comment]
It is unstable again, and force-stop doesn't fix anything. I don't understand wich conditions makes the app unstable and i find annoying to reinstall it at every crash.

**Comment by zoff99** [comment]
@stemy2 
is the icon in the notificationbar a circle or a filled circle, or a circle with a horizontal bar?
