### ISSUE TITLE
TRIfA shows me online, but nobody else

### ISSUE THREAD

**Issue by 2011** [zoff99/ToxAndroidRefImpl#310]
**Describe the bug**

App displays everyone else (including EchoBot and PublicChat users) offline

**To Reproduce**

1. Start app
2. App shows "Tox Service: ONLINE [TCP]"
3. App shows large red circle (and small green one) for EchoBot
4. EchoBot does not reply to "!info"
5. For PublicChat, app shows one active user (myself) and 200 offline users

**Expected behavior**

Expect to see others online

**Your system information:**
 - TRIfA Version: [1.0.123]
 - App from Google-Play / F-Droid / Github-Releases / other: [F-Droid]
 - Android OS Version: [Android 10 (crDroid)]
 - Device: Xiaomi Mi A3
 
 **Additional context**
 Worked about a year ago, then just stopped working.

**Comment by zoff99** [comment]
```App shows large red circle (and small green one) for EchoBot```
the large circle indicates the online status. the large red circle means that friend is offline.
echobot removes friends after a while of inactivity.

PublicChat was removed a long time ago.

do you have other friends (apart from echobot) in your contact list ?

**Comment by 2011** [comment]
> PublicChat was removed a long time ago.

I didn't know that. Maybe the app should have notified me somehow

> do you have other friends (apart from echobot) in your contact list ?

No I don't. Need to have it work well before pushing friends to install it. :) I don't usually keep it running, because it uses so much battery and bandwidth. I (recently) learned about the push notifications app, but I don't have Google play services at all on the device. Maybe you could add (to F-Droid) a push notifications app without FCM.

I have attached a screenshot. The contact list shows "never" in the EchoBot entry, as if I hadn't sent "!info" to the EchoBot before. I get the same thing with Skupina Robot [Toktok] (don't know if that remains working, but if it does, it represents a second manifestation of the problem).

![trifa](https://user-images.githubusercontent.com/550150/141052652-874a7f6b-9671-4730-965c-8535069b9a38.png)

Thank you for your help.

**Comment by zoff99** [comment]
yes the big red circle means "offline". echobot has removed your from its friends most likely.

**Comment by zoff99** [comment]
push notifications also work without google

**Comment by 2011** [comment]
> yes the big red circle means "offline". echobot has removed your from its friends most likely.

Does that mean it has blocked me permanenty? How did it become friends with me in the first place? Does some way exist to add myself back to its friend list?

> push notifications also work without google

But I don't have access to the Play Store. Doesn't it make sense to create a FCM-free push notification companion for F-Droid?

**Comment by zoff99** [comment]
the are all support questions. it's not a bug.
please join either matrix oder IRC for more help.

**Comment by 2011** [comment]
@zoff99 No support resources using the Tox network?
