### ISSUE TITLE
Clarify how the import feature works

### ISSUE THREAD

**Issue by ghost** [zoff99/ToxAndroidRefImpl#315]
Can we describe how import feature should work? I'm especially interested in

1. Is it possible to import chats?
2. Is it possible to restore profile? 

Ad 1.
No idea how to do it currently.

Ad 2.
I did it, but outcome is unexpected, see below.
1. On a device with Android i have `Trifa` installed with some chats
2. I do Trifa > Menu > Maintenance > EXPORT ENCRYPTED TOX SAVEDATA
3. I do Trifa > Menu > Maintenance > EXPORT ENCRYPTED FILES
4. I do Trifa > Menu > Maintenance > EXPORT ENCRYPTED CHATS
5. Now, reinstall Android (and Trifa) on the device
6. Do Trifa > Menu > Maintenance > IM-port TOX SAVEDATA

Now
Some account is created

While I expect
My old account is restored, ideally with previous chats or at least contact list.

I compared
* previous account public key with
* current account public key

and they differ.

Is it intentional, or i'm missing something?

Couldn't find better channel for async discussion so, writing here .. .

**Comment by ghost** [comment]
I have a progress.

So this time I did
1. Logout current account
2. Do Trifa > Menu > Maintenance > CLEAR GLIDE CACHE
3. Do Trifa > Menu > Maintenance > RUN VACUUM ON SQL DATABASE
4. Do Trifa > Menu > Maintenance > RESET FAVORITE EMOJI LIST
5. Do Trifa > Menu > Maintenance > DELETE ALL AVATAR ICONS
6. Do Trifa > Menu > Maintenance > IM-port TOX SAVEDATA

Now
1. Profile identity is restored
2. Contact list is restored
3. Chats are missing

This is good enough, I can live without older chats.

Thanks for awesome Tox client :+1:

**Comment by zoff99** [comment]
importing of chats and filetransfers is not yet supported.

**Comment by ghost** [comment]
Good to know, thanks! :+1: 

Assuming some or all steps from https://github.com/zoff99/ToxAndroidRefImpl/issues/315#issuecomment-1008264835 are required, maybe it would be good to think of
1. Add the info to Github README  - the cheapest
2. Add the info in the app while doing import - more expensive, but more user friendly
3. Make the app do the steps during the import - the most expensive, but best user-friendly?

Beside that, we can close it now?

**Comment by zoff99** [comment]
you can help in making a documentation for it

**Comment by ghost** [comment]
> you can help in making a documentation for it

Just created a MR, see https://github.com/zoff99/ToxAndroidRefImpl/pull/316
