### ISSUE TITLE
Push "Tox Push Message App" to F-droid

### ISSUE THREAD

**Issue by ghost** [zoff99/ToxAndroidRefImpl#319]
**Describe the solution you'd like**
Like the topic.

Trifa it's already on F-droid, see https://f-droid.org/en/packages/com.zoffcc.applications.trifa/

Does it make sense to put the push message app as well?

**Comment by zoff99** [comment]
f-droid does not allow apps with google FCM libraries in them. that's why the app is seperate from TRIfA

**Comment by ghost** [comment]
Oh, that makes sense. So let's close it?

**Comment by zoff99** [comment]
ok lets close it.

**Comment by 2011** [comment]
@zoff99 Why not build a version of the Tox Push Message App without the Google FCM libraries exclusively for F-Droid?
