### ISSUE TITLE
some Tox clients handle UTF-8 strings in a different way

### ISSUE THREAD

**Issue by 04533** [zoff99/ToxAndroidRefImpl#325]
Writing from Trifa to aTox, the text arrives with strange characters.
I really don't know where the problem is coming from. If from Trifa or aTox.
Im a regular user. Just wanted to show this.

 - TRIfA Version: [1.0.152]
 - App from F-Droid
 - Android OS Version: [Android 10]
 - Device: Nokia 5.1 Plus
 
![image](https://user-images.githubusercontent.com/6833516/208057718-6a006d9d-1c35-4438-bc20-8249b4367902.png)

**Comment by zoff99** [comment]
The problem is a bug in aTox. TRIfA uses an enhanced text message format (and so does Antidote for iOS) https://github.com/zoff99/c-toxcore/blob/zoff99/zoxcore_local_fork/docs/message_v3_alternate_docs.md .
all other major Tox Clients can handle this properly, only aTox does not.
the aTox author is aware of this issue, but has decided not to fix it for the time being.

**Comment by davidhedlund** [comment]
Hello, and thank you for your contribution to 

> The problem is a bug in aTox. TRIfA uses an enhanced text message format (and so does Antidote for iOS) https://github.com/zoff99/c-toxcore/blob/zoff99/zoxcore_local_fork/docs/message_v3_alternate_docs.md . all other major Tox Clients can handle this properly, only aTox does not.

Not only aTox, the same issue also occurs with qTox.

> the aTox author is aware of this issue, but has decided not to fix it for the time being.

I could not find it at https://github.com/evilcorpltd/aTox/issues, can you please try to find the issue link?

**Comment by zoff99** [comment]
it only occurs with newer [TokTok/qtox](https://github.com/TokTok/qTox/) versions. those are updated to Qt6 which seems to have different utf-8 handling.
the toktok devs are debating how to handle this, and no decision has been reached yet.

**Comment by davidhedlund** [comment]
> it only occurs with newer [TokTok/qtox](https://github.com/TokTok/qTox/) versions. those are updated to Qt6 which seems to have different utf-8 handling. the toktok devs are debating how to handle this, and no decision has been reached yet.

Thank you.

Would it be possible for you to share the issue links for both of the following repositories?
* https://github.com/TokTok/qTox/issues
* https://github.com/evilcorpltd/aTox/issues

Having those links would be very helpful for me to keep track of any ongoing discussions or updates. If such issue links are not available, please let me know-I'd be happy to submit the issues myself.

**Comment by zoff99** [comment]
the topic was discussed via Tox Group chat. i am not sure if github issues were opened.

**Comment by davidhedlund** [comment]
> the topic was discussed via Tox Group chat. i am not sure if github issues were opened.

I submitted them:
* https://github.com/evilcorpltd/aTox/issues/1302
* https://github.com/TokTok/qTox/issues/591

Thank you for all your quick replies!

**Comment by zoff99** [comment]
Toktok/qtox fixed the issue with https://github.com/TokTok/qTox/pull/513

**Comment by davidhedlund** [comment]
> Toktok/qtox fixed the issue with [TokTok/qTox#513](https://github.com/TokTok/qTox/pull/513)

Yea, I know (see above). Only aTox to be done:
* https://github.com/evilcorpltd/aTox/issues/1302
