### ISSUE TITLE
[BUG] Opening files (videos) from file transfers / scoped storage

### ISSUE THREAD

**Issue by 0xlne** [zoff99/ToxAndroidRefImpl#334]
**Describe the bug**

**To Reproduce**
1. Send file to peer
2. Click on export file
3. Toast received that the file has been exported
4. File inaccessible to apps other than Trifa; video files unplayable (not found by other apps like VLC).

**Expected behavior**
Files accessible for other apps like video players, PDF readers, file managers etc.

**Your system information:**
 - TRIfA Version: 1.0.157
 - App from Google-Play / F-Droid / Github-Releases / other: F-Droid
 - Android OS Version: Android 11
 - Device: Nubia RedMagic 6, Samsung Galaxy Note 10+ 

**Add screenshots, if possible**

**Additional context**
I presume the error is due to scoped storage being enforced from Android 11 onwards, meaning /sdcard/Android/data/xxx is only accessible to the app (uid/gid) that owns/created the folder, even for reading.
A quick & dirty workaround would be an option/toggle/radio button in settings, to select the file export strategy, much like OsmAnd, which gives you a list of possible locations.
Example:
1: the current one, for whatever reason: /sdcard/Android/data/com.zoffcc.applications.trifa
or
2: /sdcard/Downloads/ (with a warning of lack of security).

I saw that #230 was raised to submit a similar issue, which became more apparent since that time, due to more users being on Android 11/12.

**Comment by zoff99** [comment]
the files are accessible to filemanagers. sadly most phones come with filemanagers pre-installed that are broken.
if you install https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/ it will ask for access and allow you to read /sdcard/Android/data/ directory

**Comment by zoff99** [comment]
also the newest version of TRIfA will allow you to open the exported file directly from the Messageview
