### ISSUE TITLE
File transfers in text groups

### ISSUE THREAD

**Issue by 0xlne** [zoff99/ToxAndroidRefImpl#335]
**Is your feature request related to a problem? Please describe.**
Ability to send file transfers in groups, not just 1:1.

**Describe the solution you'd like**
As above.

**Your system information:**
 - TRIfA Version: 1.0.157
 - App from Google-Play / F-Droid / Github-Releases / other: F-Droid
 - Android OS Version: Android 11
 - Device: Nubia RedMagic 6, Samsung Galaxy Note 10+

**Describe alternatives you've considered**
Session, Element (Matrix).

**Additional context**
It would be useful to be able to share files in groups.
The downside being potential high resource/device/network usage, since the transfer would hang until all recipients would have processed (accepted, declined) file transfers. A workaround could be user configurable timeouts or just make sure all recipients have autoaccept all types of file transfers in settings (which already exists).
Meaning the file transfer would need to exist in as many parallel streams as there would be users in that group.

**Comment by zoff99** [comment]
toxcore is currently not able to do this. so this is out of scope for TRIfA.
you can add an issue at https://github.com/TokTok/c-toxcore/issues
