### ISSUE TITLE
Random default friend

### ISSUE THREAD

**Issue by Chromatamata** [zoff99/ToxAndroidRefImpl#345]
Hi, I'm sorry but I'm really confused. Who is the random default friend I automatically have after a first-time, clean install of TRIfA? I should not have any friends if I haven't added any, should I? Also is there any documentation that covers issues like this so I don't have to keep bugging you with annoying questions like this?

**Comment by zoff99** [comment]
that is the echobot (https://github.com/alexbakker/EchoBot), which is has been temporarily shutdown because of: https://github.com/TokTok/c-toxcore/issues/2178
