### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by mveljko78** [zoff99/ToxAndroidRefImpl#381]
It seems I have a problem with push notifications. I have installed trifa and push notify app on two phones and configured both of them as necessary...but push notifications are not arriving. Am I missing something?

**Comment by zoff99** [comment]
can you please give some more details?
does your TRIfA show your push url/token in the profile?
are you using google FCM for push (or gotifyUP , or ntfy) ?
does the push url actually get triggered (how do you trigger push, by sending a message with another client. which one) ?
does the other tox client show your push url/token in the friend settings?
can you activate the debug setting in the push app?

**Comment by mveljko78** [comment]
yes, TRIfA shows push url in the profile
I am using FCM ( I selected prefer FCM checbox in the Tox notify app)
if I long press on the message and click on the i button to check message info it says: sent_push: 1
I am using TRIfA on both Android phones
Debug setting is activated

**Comment by zoff99** [comment]
maybe you can contact me on Tox to debug this further? if this is ok for you?

**Comment by mveljko78** [comment]
that would be great! what is your ID ?

**Comment by mveljko78** [comment]
Here is my id

tox:3B8E1E005EA2479DEB6CCDB09D5BDE6FD9FBEFA75829E84422F4B0F8CEAD443B169C18E2C98C

pet, 9. dec 2022. 10:09 Zoff ***@***.***> је написао/ла:

**Comment by mveljko78** [comment]
and now? I have turned off battery savings mode

**Comment by mveljko78** [comment]
I have built all over again ,and app is now in battery saving mode, icon is
red (-1/-1/-1)
Could you now try to ping me? App should wake up? And show your message?

**Comment by mveljko78** [comment]
tox:3B8E1E005EA2479DEB6CCDB09D5BDE6FD9FBEFA75829E84422F4B0F8CEAD443B169C18E2C98C

pet, 9. dec 2022. 10:37 Zoff ***@***.***> је написао/ла:

**Comment by zoff99** [comment]
i guess your ID has changed, i don't see you inline anymore. the ID only works for 1 invitation.

**Comment by mveljko78** [comment]
I see
So every time I need to copy it again?

tox:3B8E1E005EA2479DEB6CCDB09D5BDE6FD9FBEFA75829E84422F4B0F8CEAD443B0D507CBCB61E

pet, 9. dec 2022. 22:16 Zoff ***@***.***> је написао/ла:

**Comment by zoff99** [comment]
add it , waiting for you to come online ...

**Comment by mveljko78** [comment]
I compiled after migrate to androidx. With normal compilation its not an issue
