### ISSUE TITLE
No unsecure_export_savedata.tox file in vfs_export

### ISSUE THREAD

**Issue by Holzl** [zoff99/ToxAndroidRefImpl#407]
Hello, i've been trying to export my profile from TRIfA in order to import it in QTox on my desktop but can't find the .tox file

I go to Maintenance
Click on EXPORT TOX SAVEDATA *UNSECURE*
A popup says Tox Savedata File will be exported unencrypted to this location : /storage/emulated/0/Android/data/com.zoffcc.applications.trifa/files/vfs_export//unsecure_export_savedata.tox
When I go to the directory, I can't find the said file (i checked the invisible files and tried to do the same from my desktop)

I would really like to use the file to connect to QTox to avoid sending all my contacts another request and have 2 profiles.

I'm using
 - TRIfA Version: [1.0.205]
 - Apk downloaded from F-Droid
 - LineageOS 18.1 : [Android 11]
 - Device: Samsung Galaxy A5 2017

I've searched but only seen people having the opposite problem (trying to import a profile in TRIfA)

Thanks in advance for your help

**Comment by zoff99** [comment]
what file explorer do you use to check if the file is there?
and did you actually press "OK" to start the export?

**Comment by Holzl** [comment]
I pressed OK and I use the Android base file explorer, I just now updated LineageOS to the latest version and it worked

**Comment by zoff99** [comment]
very strange. do you know what the issue was?

**Comment by Holzl** [comment]
No idea, maybe the file explorer or the writing permission of TRIfA, Lineage sometimes blocks the permissions automatically for some reason and I have to change it back manually

**Comment by zoff99** [comment]
this directory is chosen because the app does not need any special permission to write to it.

**Comment by zoff99** [comment]
is this issue now fixed?

**Comment by Holzl** [comment]
yes thank you
