### ISSUE TITLE
Can not send Message when Friend is offline

### ISSUE THREAD

**Issue by syedubair** [zoff99/ToxAndroidRefImpl#41]
#### Expected behavior
The app should be able to send messages to friends like it sends to the bot. 

#### Actual behavior
The app is unable to send a message to a friend. The send button doesn't work in a friend's chat. So we can't send any messages. 

#### How to reproduce
Launch the app. 

Add a friend. 

Open his/her ID. 

Try to send a message. 

You won't be able to send anything as the send button doesn't work. 

* App: TRIfA
* Operating system:Android Nought(7)
Moto g5 plus

#### Recording Of The Bug
https://youtu.be/if7H2u4Id2Y
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedubair/app-crashes-while-renaming-a-note-written-in-notepad">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by zoff99** [comment]
from the video i can see that your friend has not accepted your friendrequest yet.
your friend needs to accept the request and has to be online for you to send a message
