### ISSUE TITLE
can not send File while Friend is offline

### ISSUE THREAD

**Issue by darewealth** [zoff99/ToxAndroidRefImpl#42]
#### Expected behavior
Clicking on attach icon, i should be able to  attach any file and send to the recipient.

#### Actual behavior
When i click on attach icon it unable to attach the attach button didn’t work

#### How to reproduce
(1)	Download[ TRIFA ](https://play.google.com/store/apps/details?id=com.zoffcc.applications.trifa) application 

(2)	 launch It and open add a friend

(3)	Go to chat and trial to attach 

Device used: Gionee P5 mini

Operating system: Android version 5.1

*App version: 1.0.14 

#### Recording Of The Bug
https://youtu.be/DuWQy_3Val8
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@darewealth/bug-found-in-trifa-app-while-pressing-attach-icon">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by zoff99** [comment]
@darewealth thank you for your bugreport. you need to wait until your friend is online (green icon) to send messages or send files.
TRIfA does not yet have faux-offline messaging.
Tox does not have offline Messages (since there are no central servers).

please try again when your friend is online

**Comment by katcom** [comment]
@zoff99 
It is possible to write a function, that checks whether or not the friend is online, to re-send message when he/she becomes indeed online?

**Comment by zoff99** [comment]
yes it is possible. if somebody writes the code and makes a PR

**Comment by JeanPaulLucien** [comment]
@zoff99, but does client send file while in background if friend bring in online?
