### ISSUE TITLE
File transfer stuck on queue 

### ISSUE THREAD

**Issue by vehosah** [zoff99/ToxAndroidRefImpl#445]
**Describe the bug**
File stuck on queue forever 

**To Reproduce**
1. Go to 'chat' '
2. Click on 'link 
3. Scroll down to 'gallery 
4. Click on the photo
5. Click on yes transfer 
6. Stuck on queue forever 
**Expected behavior**
I expected the file to be transferred normally 

**Your system information:**
 - TRIfA Version: [1.0.224]
 - App from  [F-Droid]
 - Android OS Version: [Android 12 and 13]
 - Device: Nokia 5.4 

**Add screenshots, if possible**

**Additional context**

**Comment by zoff99** [comment]
what client is the other person using? filetransfers sometimes have stability issue. that is a know problem in toxcore.
if both parties are using TRIfA then this should not happen.
you can see in friend settings what capabilites the other persons client has.

**Comment by vehosah** [comment]
Uh where are these friends settings?

**Comment by zoff99** [comment]
long press on the friend in the list

**Comment by vehosah** [comment]
Hey this stuck on sending seems to be present when the other client is not online, is it true?

**Comment by zoff99** [comment]
yes, the other client has to be online for a filetransfer to work.

**Comment by vehosah** [comment]
If I long press on the friend I can see info, create group chat, create audio chat, add as proxy and delete

**Comment by vehosah** [comment]
> yes, the other client has to be online for a filetransfer to work.

Oh thanks I didn't know that

**Comment by zoff99** [comment]
since there are no server when using tox, things only work when both clients are online

**Comment by vehosah** [comment]
Oh okay thanks

**Comment by zoff99** [comment]
is the issue now solved for you?

**Comment by vehosah** [comment]
I don't know i guess
