### ISSUE TITLE
Logout/Login option is not very clear

### ISSUE THREAD

**Issue by darewealth** [zoff99/ToxAndroidRefImpl#45]
#### Expected behavior
Clicking on Logout/Login, I should be able to Logout/Login

#### Actual behavior
When i click on Logout/Login it didn’t work at all.

#### How to reproduce
(1) Download TRIFA application

(2) launch It and open go to menu

(3) click on Logout/Login

Device used: Gionee P5 mini

Operating system: Android version 5.1

*App version: 1.0.14

#### Recording Of The Bug
https://youtu.be/2AZqaJmQSG4
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@darewealth/bug-found-in-trifa-app-while-click-on-logout-login">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by zoff99** [comment]
there is no bug. you can only logout after you are online. and vice versa
