### ISSUE TITLE
Message to Private Group is not received when group member is offline

### ISSUE THREAD

**Issue by alma06132** [zoff99/ToxAndroidRefImpl#455]
**Describe the bug**
I have a test Private Group with my 2 phones, and messages are not received when one client is offline.
At the same time, messages sent directly to the same client when he is offline arrive when he return to the network.
Versions of clients are the same (latest 1.0.228 30 March 2024), one client is on Android 14 and another is on Android 10

**To Reproduce**
- One client has running Android client, another is switched off (not running)
- One client send text message to Private Group with one another member which is offline
- Second client open client and became online and wait for 10 minutes but message is not delivered

**Expected behavior**
I expect that if direct messages are delivered to offline client when he come back to online then messages in private group also could be added to queue and delivered to offline members when they became online.

**Your system information:**
 - TRIfA Version: [latest 1.0.228 30 March 2024 on both phones]
 - App from F-Droid
 - Android OS Version: [Android 10, Android 14]
 - Device: Samsung Galaxy S9+ (Android 10) and Samsung Galaxy S22 Ultra (Android 14), both with latest official firmware

**Comment by zoff99** [comment]
this is not possible with toxcore. you can open an issue in the toxcore repo if you wish: https://github.com/TokTok/c-toxcore

**Comment by zoff99** [comment]
TRIfA has NGC group history sync only for public groups and also only for a 130 minutes into the past

**Comment by alma06132** [comment]
> TRIfA has group history sync only for public groups and also only for a 130 minutes into the past

what is a difference between Private and Public Group? didn't find anything about it on Tox site

**Comment by zoff99** [comment]
public NGC groups can be joined by anyone that has the groupID.
a private group can only be joined if you get invited by someone who is already a group peer.

**Comment by zoff99** [comment]
@alma06132 can i close this issue?

**Comment by alma06132** [comment]
@zoff99 , yes, sure
