### ISSUE TITLE
call icon not responding on Trifa

### ISSUE THREAD

**Issue by cckole** [zoff99/ToxAndroidRefImpl#46]
#### Expected behavior
i expected the call icon to respond when clicked to call a friend.

#### Actual behavior
There was no response when clicked,it was just stagnant.

#### How to reproduce
download Trifa from google play and install,launch the application, add a friend, click the call icon to call a friend.

* Operating system: Android version 5.1 : 

* Device used:  Gionee P5 mini

* App version: 1.0.14

#### Recording Of The Bug
https://youtu.be/axdr-mT72IY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ckole/call-icon-not-responding-on-trifa">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by zoff99** [comment]
your friend is not online. so no call is possible.
