### ISSUE TITLE
WiFi-only mode

### ISSUE THREAD

**Issue by JFreegman** [zoff99/ToxAndroidRefImpl#49]
Tox uses lots of of data even with UDP disabled, which means that if you're not connected to WiFi it could use up your mobile data pretty fast without even realizing it. It would be nice to have a WiFi-only option similar to what Antox has, so that you don't have to worry about logging out of your Tox client every time you don't have a WiFi connection.

**Comment by zoff99** [comment]
@JFreegman 
until this is implemented you can use this workaround (i think starting from Android 6.0 and up):

goto **"App info"** -> **"Data usage"** -> enable **"Disable all cellular data access"**

**Comment by ilovelinux** [comment]
If the way that @zoff99 wrote doesn't work and your smartphone is rooted you can use AFWall+ to deny data connections.

**Comment by JeanPaulLucien** [comment]
@JFreegman , do you share your internet connection by mobile device?
