### ISSUE TITLE
trifa does not release microphone lock upon call end

### ISSUE THREAD

**Issue by vn971** [zoff99/ToxAndroidRefImpl#57]
#### Your system information:
TRIfA Version:  1.0.15 (F-Droid)
Android OS Version: 8.1.0
Device: Nexus 6p (angler), CopperheadOS

#### Please describe your issue in as much detail as possible:
Trifa does not release microphone lock upon call end. Attempting to use mic in any other application fails.
If I return to trifa and press Menu > Exit, I get the working mic back.

#### Steps for reproducing this issue:
* start trifa
* wait for connection to establish
* wait for EchoBot to appear online
* call EchoBot
* end call
* switch to another application, try to use the mic

The attempt will fail. As already said earlier, "exiting" trifa makes the mic work again.

**Comment by krasjev** [comment]
I can confirm a similar experience to the point that I heard myself speak when trying to make another phone call after a Trifa session.

This is version 1.0.16 on Lineageos 14.1 Samsung S4 Mini.

**Comment by zoff99** [comment]
this should be fixed now
