### ISSUE TITLE
Crash on Exit, leaves notification

### ISSUE THREAD

**Issue by vn971** [zoff99/ToxAndroidRefImpl#58]
#### Your system information:
TRIfA Version:  1.0.15 (F-Droid)
Android OS Version: 8.1.0
Device: Nexus 6p (angler), CopperheadOS

#### Please describe your issue in as much detail as possible:
See subj.

#### Steps for reproducing this issue:
* start trifa
* wait for connection to establish
* set status to Away, set "online" status to Available
* press Menu > Exit

Expected at this point:
* trifa exits fully, with nothing active left at all

Actually:
* persistent notification remains telling trifa is "OFFLINE".

#### Screenshots (if possible):
![trifa-offline-bug](https://user-images.githubusercontent.com/1547617/39392567-8b4f4afe-4ac0-11e8-81c7-40a4c79ff1b9.png)

**Comment by krasjev** [comment]
same experience here with version 1.0.16

**Comment by ilovelinux** [comment]
It seems to be fixed in 1.0.17

**Comment by vn971** [comment]
@ilovelinux I'm not using trifa at the moment, so I just assume it's the case. Thanks, closing.

**Comment by zoff99** [comment]
there still are some crashes on exit

**Comment by zoff99** [comment]
fixed by 3789db4f33e10f0645a20cbe0bad79125ccce50a
and by 9566b839be76f747c7e2366fce964cd95f84ce6a
