### ISSUE TITLE
No video rendered in Toxic client

### ISSUE THREAD

**Issue by krasjev** [zoff99/ToxAndroidRefImpl#64]
#### Your system information:

TRIfA Version: 1.0.16

App from Google-Play / F-Droid / other: F-droid

Android OS Version: lineageos 14.1

Device: samsung s4 mini

#### Please describe your issue in as much detail as possible:
When making a video conference with Toxic client no video is send to or shown on Toxic side.
Testing Toxic client with Echobot, the video works just fine.

Video from Toxic is rendered fine in Trifa.
Sound works well both ways.

Toxic client:
Toxic version 0.8.2_r1820
Toxcore version 0.2.2
on Gnu/Linux

**Comment by zoff99** [comment]
@krasjev can we make a test? are you still having this issue?
