### ISSUE TITLE
JVM implementation of ToxCore

### ISSUE THREAD

**Issue by NyxCode** [zoff99/ToxAndroidRefImpl#67]
As far I know, we still don't have a Java (or other JVM language) implementation of toxcore. I believe that this could make debugging significantly easier and clients faster (no need for JNI).

**Comment by zoff99** [comment]
@NyxCode yes there is. please look at the integrations page:
https://toktok.ltd/integrations.html

pure java bindings:
https://github.com/zoff99/java_toxclient_example/tree/master/jni-c-toxcore

**Comment by NyxCode** [comment]
I'm afraid you misunderstood. The library you linked is a java binding (using JNI) for the toxcore-c-implementation. I was talking about a pure JVM implementation of toxcore.
