### ISSUE TITLE
Copy message contents to clipboard

### ISSUE THREAD

**Issue by tortugaverde98** [zoff99/ToxAndroidRefImpl#72]
#### Your system information:
TRIfA Version:
1.0.16

App from Google-Play / F-Droid / other:
F-droid

Android OS Version:
7.1.2
Device:
S5

#### Please describe your issue in as much detail as possible:
Long press contents of message does not present a context menu, where you would be able to copy, select all, etc. This is required to load the contents of a message to the clipboard, and paste to another app. Super basic functionality.

#### Steps for reproducing this issue:
Long press contents of a message, nothing happens.

#### Screenshots (if possible):
n/a

**Comment by zoff99** [comment]
long click on a message next to the messge bubble to select it

**Comment by rainbyte** [comment]
After trying many times to copy I came here to report this.
I think it is a bit difficult to find this feature.

**Comment by zoff99** [comment]
any help with the code is welcome

**Comment by rainbyte** [comment]
@zoff99 I have made PR #143 to workaround this issue
