### ISSUE TITLE
No backup/restore function

### ISSUE THREAD

**Issue by tortugaverde98** [zoff99/ToxAndroidRefImpl#73]
#### Your system information:
TRIfA Version:
1.0.16

App from Google-Play / F-Droid / other:
F-droid

Android OS Version:
7.1.2

Device:
S5

#### Please describe your issue in as much detail as possible:
In Maintenance there is not backup or restore function.

#### Steps for reproducing this issue:
na

#### Screenshots (if possible):
na

**Comment by moriel5** [comment]
I am joining this bug report, as I cannot use my existing profile with TRIfA, and I regularly need to have modularity with my accounts, due me testing different devices and OS's.

I had installed the F-Droid version, and upon seeing that I do not have an option to import my existing profile (something that AnTox  can do), I had installed the development version, hoping that the profile import/export feature was at least being tested, but to no avail.

**Comment by smaragdus** [comment]
An option to import/export Tox ID is absolutely essential for me.

**Comment by zoff99** [comment]
if you want to program it you are welcome to make a PR

**Comment by smaragdus** [comment]
@zoff99 

Unfortunately I am not a programmer, just a user,

On desktop Tox client I have a huge list of contacts, re-adding them one by one on Android client would be a hard and time-consuming task.

I suppose you might request help for import/export Tox ID.

**Comment by jeee** [comment]
Being able to safely store and restore your ID and contacts seems a basic requirement for a communication tool I assume? Any progress on this?

**Comment by akontsevich** [comment]
Very strange! This feature was available 7 years ago in all tox cliens (uTox, qTox, etc). Why you force us to create new TOX ID, @zoff99?! And if I want to leave TRIfA I can't do this as well -  so I'm limited only to this client. Where is the freedom?!

**Comment by akontsevich** [comment]
> if you want to program it you are welcome to make a PR

@zoff99  simple question: you this app for yourself or for people?!

**Comment by zoff99** [comment]
there is an export / import function for a long time. have a look at the documentation: https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/import-export.md

**Comment by akontsevich** [comment]
> there is an export / import function for a long time. have a look at the documentation: https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/import-export.md

I saw it. It is VERY complex and unclear. I can't select/import/export from/to arbitrary file. You create new TOX ID on start for me which I do not need. 

aTox allows to import `name.tox` on the first start and only 1 export item in menu - works just fine. Same for uTox/qTox, etc. Why do you have 3 import/export options in TRIfA and process is so complex and I can't select custom path, find this file, etc? It is very confusing! Can we have standard feature for Tox clients, please? Import/Export only `1 *.tox` file? A [lot of people](https://github.com/Zoxcore/trifa_material/issues/253#issuecomment-2498928260) ask for this. Thanks!
