### ISSUE TITLE
Rebuild with toxcore v0.2

### ISSUE THREAD

**Issue by physkets** [zoff99/ToxAndroidRefImpl#75]
I'm currently using version 1.0.16 from F-Droid, and it says that it is built against c-toxcore v0.1.11

Can it be re-built against the latest c-toxcore v0.2.x ?

**Comment by zoff99** [comment]
it is using a much newer version of toxcore than 0.1.x

**Comment by physkets** [comment]
The interface used to indicate the specific version of toxcore it was built with. Does it no longer do so?
