### ISSUE TITLE
Sometimes "waiting for Orbot" goes on forever

### ISSUE THREAD

**Issue by ilovelinux** [zoff99/ToxAndroidRefImpl#84]
#### Your system information:
TRIfA Version: 1.0.17

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: Android 7.0

Device: Not related to the issue

#### Please describe your issue in as much detail as possible:
Sometimes "waiting for Orbot" goes on forever.

#### Steps for reproducing this issue:
* Enable `Settings -> General -> enable Tor Proxy`
* Restart the app until it bugs

#### Screenshots (if possible):
![Screenshot](https://user-images.githubusercontent.com/9268789/45818584-a8bdd500-bcd1-11e8-86b2-490b6e34d22f.png)

**Comment by zoff99** [comment]
the latest version of orbot seems to have some issues. not sure if this is an orbot issue or trifa issue.
try with an older version of orbot as a workaround

**Comment by JeanPaulLucien** [comment]
Is Orbot installed?

**Comment by IamPARANOID** [comment]
+1/Also affected.
Tried with several older versions of Orbot but still same result.
Seems to be not "sometimes" but "always" that this happens...

**Comment by tenderizer** [comment]
im getting the same issue now
trifa: 1.0.21
orbot: 16.2.0-RC-tor-0.4.2.7-1-geed732a3

**Comment by zoff99** [comment]
@tenderizer latest is 1.0.48

https://f-droid.org/packages/com.zoffcc.applications.trifa/
