### ISSUE TITLE
Update ToxCore to 0.2.8.

### ISSUE THREAD

**Issue by SC1040-TS2** [zoff99/ToxAndroidRefImpl#90]
#### Your system information:
TRIfA Version: 1.0.19

App from Google-Play / F-Droid / other: F-Droid

Android OS Version: 6.0.1

Device: Samsung GS5

#### Steps for reproducing this issue:
your text here Whan initially loading the app, the version of ToxCore used is displayed briefly. Currently it is 0.2.7, but as of two weeks prior it is no longer up to date.

**Comment by zoff99** [comment]
TRIfA is always using a toxcore version that is more advanced than the current release
