### ISSUE TITLE
Feature request: copy and share message and flie received

### ISSUE THREAD

**Issue by linsui** [zoff99/ToxAndroidRefImpl#93]
#### Your system information:
TRIfA Version:
1.0.20
App from Google-Play / F-Droid / other:
 F-Droid
Android OS Version:
9
Device:
Xiaomi Mi 6

**Comment by zoff99** [comment]
long click to select

**Comment by linsui** [comment]
I find if I click on the text or image I can't select it. Only click on blank space in message box can I select it. Besides, is there any way to share image to other conversation or app?

**Comment by zoff99** [comment]
that function is not implemented yet. you are welcome to help and code it.
we need some help.
