### ISSUE TITLE
no ringtone on incoming call

### ISSUE THREAD

**Issue by Nokia808** [zoff99/ToxAndroidRefImpl#96]
#### Your system information:
TRIfA Version: 1.0.21

App from Google-Play / F-Droid / other: from Google play

Android OS Version: Android 8.1.0

Device: Honor 8X (JSN-L22)

#### Please describe your issue in as much detail as possible:
When some one call me by TRIFA, there will be no any ringing ! So, how can I know that some one call me !
I enabled all setting of ringing notifications but no ringing alarm when some one call me on TRIFA.

**Comment by Nokia808** [comment]
No any comment from developer(s) about this issue till now !! Is it significant or not ? Please do you need any additional information ? Can I help you further to solve this issue ? I'm not programmer but can I send you more data being useful to you to fix this issue ?

If you are not interested to fix this problem, then kindly inform me to switch to other application. Currently your application useless on my device: no ringing voice at all when some one call me using Tox protocol.

**Comment by quantumpacket** [comment]
I'm having the same issue. I turned on all notifications, no audio or notifications come through. I doesn't even notify me if someone messages me, let alone when someone tries to call me. I have to have the app open for me to have any visual notification at all.

**Comment by physkets** [comment]
I started facing this after an update to Android 9.0 . It was fine for me until I was on 8.1 . https://github.com/zoff99/ToxAndroidRefImpl/issues/103

**Comment by zoff99** [comment]
It's not a bug, this feature is just not coded yet.
how ever wants to code it, PRs welcome ...

**Comment by zoff99** [comment]
added in https://github.com/zoff99/ToxAndroidRefImpl/commit/7d4261645f29b550259602737de4f356cf147670
