### ISSUE TITLE
[Feature request] Add "import Tox ID" option.

### ISSUE THREAD

**Issue by Nokia808** [zoff99/ToxAndroidRefImpl#97]
#### Your system information:
TRIfA Version: last one
Currently, TRIFA has no option to import already created Tox ID. 
It will be nice to add such option which is already existing in Antox.

**Comment by smaragdus** [comment]
Without an option to import/export Tox ID this Tox client is useless to me- on Android I don't need a new Tox ID but to be able to import my Tox ID I use on Desktop.

**Comment by Duehok** [comment]
Same for me, the app is completely useless without this feature. I am not going to send a new friend request to every single contact I have. And what about somebody with two phones?

**Comment by DoctorSubtilis** [comment]
+1 I agree

**Comment by zoff99** [comment]
fixed in https://github.com/zoff99/ToxAndroidRefImpl/commit/adc66cad2b963dc9e1d91f4f7e8cfebcea84f944
